[default_view]

keymap = [
  { keys = ["o"], commands = ["shell nvim %s"] },
  { keys = ["e"], commands = ["open_with"] },
  { keys = ["escape"], commands = ["escape"] },
  { keys = ["ctrl+t"], commands = ["new_tab --current"] },
  { keys = ["ctrl+w"], commands = ["close_tab"] },
  { keys = ["q"], commands = ["quit --output-current-directory"] },
  { keys = ["Q"], commands = ["quit --output-current-directory"] },

  { keys = ["R"], commands = ["reload_dirlist"] },
  { keys = ["z", "h"], commands = ["toggle_hidden"] },
  { keys = ["ctrl+h"], commands = ["toggle_hidden"] },
  { keys = ["\t"], commands = ["tab_switch 1"] },
  { keys = ["backtab"], commands = ["tab_switch -1"] },
  
   # arrow keys
  { keys = ["arrow_up"], commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["arrow_left"], commands = ["cd .."] },
  { keys = ["arrow_right"], commands = ["open"] },
  { keys = ["home"], commands = ["cursor_move_home"] },
  { keys = ["end"], commands = ["cursor_move_end"] },
  { keys = ["page_up"], commands = ["cursor_move_page_up"] },
  { keys = ["page_down"], commands = ["cursor_move_page_down"] },

  # vim-like keybindings
  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["k"], commands = ["cursor_move_up"] },
  { keys = ["h"], commands = ["cd .."] },
  { keys = ["l"], commands = ["open"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"], commands = ["cursor_move_end"] },

  # { keys = ["H"], commands = ["cursor_move_page_home"] },
  # { keys = ["L"], commands = ["cursor_move_page_middle"] },
  # { keys = ["M"], commands = ["cursor_move_page_end"] },

  # { keys = ["["], commands = ["parent_cursor_move_up"] },
  # { keys = ["]"], commands = ["parent_cursor_move_down"] },

  { keys = ["c", "d"], commands = [":cd "] },
  { keys = ["d", "d"], commands = ["cut_files"] },
  { keys = ["y", "y"], commands = ["copy_files"] },
  { keys = ["y", "n"], commands = ["copy_filename"] },
  { keys = ["y", "."], commands = ["copy_filename_without_extension"] },
  { keys = ["y", "p"], commands = ["copy_filepath"] },
  { keys = ["y", "d"], commands = ["copy_dirpath"] },

  # { keys = ["p", "l"], commands = ["symlink_files --relative=false"] },
  # { keys = ["p", "L"], commands = ["symlink_files --relative=true"] },

  { keys = ["delete"], commands = ["delete_files --permanently "] },
  { keys = ["d", "D"], commands = ["delete_files --permanently "] },

  { keys = ["p", "p"], commands = ["paste_files"] },
  { keys = ["p", "o"], commands = ["paste_files --overwrite=true"] },
  
  { keys = ["r"], commands = ["rename_append_base"] },
  { keys = ["a"], commands = ["rename_append"] },
  { keys = ["A"], commands = ["rename_prepend"] },
  { keys = ["c", "w"], commands = [":rename "] },


  { keys = [" "], commands = ["select --toggle=true"] },
  { keys = ["v"], commands = ["select --all=true --toggle=true"] },
  { keys = ["V"], commands = ["toggle_visual"] },

  { keys = ["w"], commands = ["show_tasks --exit-key=q"] },
   # 修改权限  
  { keys = ["="], commands = ["set_mode"] },

  { keys = [":"], commands = [":"] },
  { keys = [";"], commands = [":"] },

  { keys = ["."], commands = [":shell "] },
  { keys = ["f", "t"], commands = [":touch "] },
  { keys = ["m", "k"], commands = [":mkdir "] },

  { keys = ["/"], commands = [":search "] },
  { keys = ["\\"], commands = [":search_glob "] },
  { keys = ["s", "f"], commands = ["search_fzf"] },

  { keys = ["n"], commands = ["search_next"] },
  { keys = ["N"], commands = ["search_prev"] },

  { keys = ["s", "r"], commands = ["sort reverse"] },
  { keys = ["s", "l"], commands = ["sort lexical"] },
  { keys = ["s", "m"], commands = ["sort mtime"] },
  { keys = ["s", "n"], commands = ["sort natural"] },
  { keys = ["s", "s"], commands = ["sort size"] },
  { keys = ["s", "e"], commands = ["sort ext"] },

  # { keys = ["m", "s"], commands = ["linemode size"] },
  # { keys = ["m", "m"], commands = ["linemode mtime"] },
  { keys = ["m", "m"], commands = ["linemode size | mtime"] },

  { keys = ["g", "r"], commands = ["cd /"] },
  { keys = ["g", "c"], commands = ["cd ~/.config"] },
  { keys = ["g", "d"], commands = ["cd ~/Documents"] },
  { keys = ["g", "p"], commands = ["cd ~/Documents/Code/Project"] },
  { keys = ["g", "h"], commands = ["cd ~/"] },
  { keys = ["?"], commands = ["help"] },
]

[task_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["home"], commands = ["cursor_move_home"] },
  { keys = ["end"], commands = ["cursor_move_end"] },

  # vim-like keybindings
  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["k"], commands = ["cursor_move_up"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"], commands = ["cursor_move_end"] },

  { keys = ["w"], commands = ["show_tasks"] },
  { keys = ["escape"], commands = ["show_tasks"] },
]

[help_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["home"], commands = ["cursor_move_home"] },
  { keys = ["end"], commands = ["cursor_move_end"] },

  # vim-like keybindings
  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["k"], commands = ["cursor_move_up"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"], commands = ["cursor_move_end"] },

  { keys = ["w"], commands = ["show_tasks"] },
  { keys = ["escape"], commands = ["show_tasks"] },
]
